version: '3'

services:
  ydlpod:
    image: jxjxjhjh/ydlpod
    container_name: pod2
    ports:
      - "8001:8001"
    volumes:
      - /var/syncthing/media/docker/ydlpod:/app/config
      - /var/syncthing/media/docker/ydlpod:/app/data
    restart: always
